version: '3.3'
services:
  eureka:
    image: pvyshnevetskyi/facedynamics:eureka0.0.3
    restart: on-failure
  comments-reactions-service:
    image: pvyshnevetskyi/facedynamics:comments0.0.5
    restart: on-failure
    depends_on:
      eureka:
        condition: service_started
  posts-service:
    image: pvyshnevetskyi/facedynamics:posts0.0.5
    restart: on-failure
    depends_on:
      eureka:
        condition: service_started
  media-service:
    image: pvyshnevetskyi/facedynamics:media0.0.5
    restart: on-failure
    depends_on:
      eureka:
        condition: service_started
  gateway:
    image: pvyshnevetskyi/facedynamics:gateway0.0.4
    restart: on-failure
    depends_on:
      eureka:
        condition: service_started
    ports:
      - '8080:8080'
  notifications-service:
    image: unfabled/facedynamics:notifications0.0.5
    restart: on-failure
    depends_on:
      eureka:
        condition: service_started
  users-service:
    image: unfabled/facedynamics:users0.0.5
    restart: on-failure
    depends_on:
      eureka:
        condition: service_started